### ISSUE TITLE
Valid arithmetic and the simple matrix multiply

### ISSUE THREAD

**Issue by Rellek72** [Xilinx/brevitas#508]
I feel like I'm overlooking something obvious, but I'm confused how to do a simple Matrix Multiply in Brevitas while maintaining quantization integrity. Similarly, addition between two QuantTensors (even from the same quantizer) seems to return an invalid quant tensor. Below is some test code demonstrating the problem; I implemented Matrix Multiply based off of the `__add__` and `__mul__` implementations in `quant_tensor.py`, under the premise that a matrix multiply of AB such that A is of dims (M,N) and B is of dims (N,L) can be considered to be M individual element-wise `__mul__` ops, and each summed with N-1 `__add__` ops for the purpose of calculating bit_width and zero_point.

```
import torch
import brevitas.nn as qnn
from brevitas.function.ops_ste import ceil_ste
from brevitas.function.ops import max_int, min_int
from brevitas.quant_tensor import QuantTensor
from brevitas.quant import Int8ActPerTensorFloat as ActQuant
pyt
def inspectTensor(x):
    x.is_valid
    print(f'  scale: {x.scale}\n  zero_point: {x.zero_point}\n  bit_width: {x.bit_width}\n\n')
    
def matMul(a, b):
    # Assuming input matrices are fully valid
    value = torch.matmul(a.value, b.value)
    scale = a.scale * b.scale
    zero_point = a.shape[1]*(a.zero_point * b.zero_point)
    signed = a.signed or b.signed
    row_bit_width = a.bit_width + b.bit_width
    max_val = 2*max_int(signed=signed, narrow_range=False, bit_width=row_bit_width)
    min_val = 2*min_int(signed=signed, narrow_range=False, bit_width=row_bit_width)
    bit_width = ceil_ste(torch.log2(max_val - min_val))
    training = a.training or b.training
    return QuantTensor(value=value,
                       scale=scale,
                       zero_point=zero_point,
                       bit_width=bit_width,
                       signed=signed,
                       training=training)

def basicMath():
    in_quant = qnn.QuantIdentity(act_quant=ActQuant, return_quant_tensor=True)
    # Data is arbitrary
    x = torch.rand((32,64))
    y = torch.rand((32,64))
    yT = torch.rand((64,32))
    x_q = in_quant(x)
    y_q = in_quant(y)
    yT_q = in_quant(yT)
    print('x_q')
    inspectTensor(x_q)
    print('y_q')
    inspectTensor(y_q)
    # Addition
    sum_xy = x_q + y_q
    print('sum_xy')
    inspectTensor(sum_xy)
    # Multiplication
    product_xy = x_q * y_q
    print('product_xy')
    inspectTensor(product_xy)
    # Matrix Multiplication
    mat_z = matMul(yT_q, x_q)
    print('mat_z')
    inspectTensor(mat_z)
    
    
basicMath()
```

Output:

```
x_q
Valid:
    is_int: True
    is_upper_b: True
    is_lower_b: True
    True
  scale: 0.00780837144702673
  zero_point: 0.0
  bit_width: 8.0


y_q
Valid:
    is_int: True
    is_upper_b: True
    is_lower_b: True
    True
  scale: 0.007808669935911894
  zero_point: 0.0
  bit_width: 8.0


sum_xy
Valid:
    is_int: False
    is_upper_b: True
    is_lower_b: True
    False
  scale: 0.007808520458638668
  zero_point: 0.0
  bit_width: 9.0


product_xy
Valid:
    is_int: True
    is_upper_b: True
    is_lower_b: True
    True
  scale: 6.0972994106123224e-05
  zero_point: 0.0
  bit_width: 16.0


mat_z
Valid:
    is_int: True
    is_upper_b: False
    is_lower_b: True
    False
  scale: 6.0961221606703475e-05
  zero_point: 0.0
  bit_width: 17.0
```
Apologies again for the relatively simple question, clarification would be greatly appreciated.
